name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint || echo "No lint script found, skipping"

    - name: Run tests
      run: npm test
      env:
        SKIP_SLACK: 1
        NODE_ENV: test

    - name: Validate configuration
      run: npm run validate
      env:
        SLACK_SIGNING_SECRET: test_secret
        SLACK_BOT_TOKEN: xoxb-test
        FIVETRAN_API_KEY: test_key
        FIVETRAN_API_SECRET: test_secret

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level moderate

    - name: Check for known vulnerabilities
      run: |
        if npm audit --audit-level moderate; then
          echo "No high or moderate vulnerabilities found"
        else
          echo "Vulnerabilities found - please review and update dependencies"
          exit 1
        fi
